apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwa-deployment
  labels:
    app: dwa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dwa
  template:
    metadata:
      labels:
        app: dwa
    spec:
      containers:
      - name: dwa-container
        image: mincho/dwa:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: dwa-service
spec:
  selector:
    app: dwa
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30000