apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwa-deployment
  labels:
    app: dwa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dwa
  template:
    metadata:
      labels:
        app: dwa
    spec:
      containers:
      - name: dwa-container
        image: mincho/dwa:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 7000